server:
  port: 1000
spring:
  profiles: node1
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://kongTao:123456@localhost:1001/eureka/
security:
  user:
    name: kongTao
    password: 123456
  enable-csrf: false
---
server:
  port: 1001
spring:
  profiles: node2
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://kongTao:123456@localhost:1000/eureka/
security:
  user:
    name: kongTao
    password: 123456
  enable-csrf: false