server:
  port: 1000
spring:
  profiles: node1
  application:
    name: eureka-server
  security:
    user:
      name: kongTao
      password: 123456
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://kongTao:123456@localhost:1001/eureka/
---
server:
  port: 1001
spring:
  profiles: node2
  application:
    name: eureka-server
  security:
    user:
      name: kongTao
      password: 123456
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://kongTao:123456@localhost:1000/eureka/